DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS medications;
DROP TABLE IF EXISTS encrypted_files;
DROP TABLE IF EXISTS doctor_availability;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS doctors CASCADE;
