// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash sql.NullString
	GoogleID     sql.NullString
	Name         sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
